service: barksh-module-intersection
frameworkVersion: "3"

provider:
  name: aws
  stage: prod
  region: us-east-1
  runtime: nodejs18.x
  memorySize: 256
  timeout: 10
  httpApi:
    cors: true
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    INTERSECTION_MONGO_DB: ${env:INTERSECTION_MONGO_DB}

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./typescript/tsconfig.build.json"
  serverless-offline:
    useChildProcesses: true
    httpPort: 4000

functions:
  AuthenticationInquiryPost:
    handler: src/handlers/authentication/post-inquiry.authenticationPostInquiryHandler
    events:
      - httpApi:
          path: /authentcation/inquiry
          method: post
